// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission10.Data;

#nullable disable

namespace Mission10.Migrations
{
    [DbContext(typeof(BowlerContext))]
    [Migration("20240326060426_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Mission10.Data.Bowler", b =>
                {
                    b.Property<int>("bowlerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("bowlerAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("bowlerCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("bowlerFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("bowlerLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("bowlerMiddleInit")
                        .HasColumnType("TEXT");

                    b.Property<string>("bowlerPhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("bowlerState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("bowlerZip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("teamID")
                        .HasColumnType("INTEGER");

                    b.HasKey("bowlerID");

                    b.HasIndex("teamID");

                    b.ToTable("Bowlers");
                });

            modelBuilder.Entity("Mission10.Data.Team", b =>
                {
                    b.Property<int>("teamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("captainID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("teamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("teamID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Mission10.Data.Bowler", b =>
                {
                    b.HasOne("Mission10.Data.Team", null)
                        .WithMany("Bowlers")
                        .HasForeignKey("teamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mission10.Data.Team", b =>
                {
                    b.Navigation("Bowlers");
                });
#pragma warning restore 612, 618
        }
    }
}
